/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <rccconfig.h>

#include "../cmsis/Device/ST/STM32F4xx/Include/stm32f446xx.h"


void tim6Config (void);
void delay(uint16_t us);
void delay_ms (uint16_t ms);
void gpioConfig(void);

int main(void)
{
	sysclkConfig();
	tim6Config();
	gpioConfig();

	while(1)
	{
		GPIOA->BSRR |= 1<<5;
		delay_ms(300);
		GPIOA->BSRR |= (1<<5)<<16;
		delay_ms(100);

	}
}

void tim6Config (void)
{
	RCC->APB1ENR |= (1<<4);
	TIM6->PSC |= 90-1;
	TIM6->ARR |= 0xFFFF;
	TIM6->CR1 |= (1<<0);             //counter enable
	while(!(TIM6->SR & (1<<0)));     // UIF update interrupt flag
}

void delay_us (uint16_t us)
{
	TIM6->CNT =0;
	while(TIM6->CNT < us);
}

void delay_ms (uint16_t ms)
{
	for (uint16_t i=0; i<ms; i++)
	{
		delay_us(1000);
	}
}

void gpioConfig(void)
{
	RCC->AHB1ENR |= (1<<0);
	GPIOA->MODER |= (1<<10);
	GPIOA->OTYPER &= ~(1<<5);
	GPIOA->OSPEEDR |= (1<<11);
	GPIOA->PUPDR &= ~((1<<10) | (1<<11));
}
