/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <rccconfig.h>

void adc_Init(void);
void adc_enable(void);

int main(void)
{
    while(1);
}

void adc_Init(void)
{
	/*
	 * enable gpio and adc clock
	 * prescaler in ccr
	 * SCAN MODE AND RESOLUTION
	 * continuous conversation
	 * sampling time for adc
	 * regular ch sequence length
	 * gpio pins
	 *
	 */
	RCC->AHB1ENR |= (1<<1);
	RCC->APB2ENR |= (1<<8);

	ADC->CCR |= (1<<16);

	ADC1->CR1 |= (1<<8);
	ADC1->CR1 &= ~(3<<24);

	ADC1->CR2 |= (1<<1);
	ADC1->CR2 |= (1<<10);
	ADC1->CR2 &= ~(1<<11);

	ADC1->SMPR2 &= ~((1<<0)|(1<<9));
	ADC1->SQR1 |= (1<<20);

	GPIOB->MODER |= 3<<0;
	GPIOB->MODER |= 3<<2;

}

void adc_enable(void)
{
	/*
	 * enable adc and wait for stability
	 */
	ADC1->CR2 |= (1<<0);
	uint32_t delay =10000;
	while(delay--);
}

void adc_start(int ch)
{
	/*
	 * set the ch sequence
	 * clear status reg
	 * start the conv by setting swstart
	 */
	ADC1->SQR3 |= 0; //clear the seq reg
	ADC1->SQR3 |= ch<<0; //write the ch number

	ADC1->SR |= 0; //sttus register temizlendi

	ADC1->CR2 |= 1<<30; // start conv

}
